import 'dotenv/config';
import { Command } from 'commander';
import { GitHubClient, parsePRUrl, parseDiff } from './github/index.js';
import { LogicReviewerAgent, ReviewOrchestrator } from './review/index.js';
import type { PRReviewResult } from './review/index.js';

const program = new Command();

program
	.name('pr-review')
	.description('AI-powered GitHub PR Review Bot')
	.version('0.1.0');

program
	.command('review')
	.description('Review a GitHub Pull Request')
	.argument('<pr-url>', 'GitHub PR URL (e.g., https://github.com/owner/repo/pull/123)')
	.option('--post-comment', 'Post review as GitHub comment')
	.action(async (prUrl: string, options: { postComment?: boolean }) => {
		const githubToken = process.env.GITHUB_TOKEN;
		const openaiKey = process.env.OPENAI_API_KEY;
		const openaiBaseUrl = process.env.OPENAI_BASE_URL;
		const openaiModel = process.env.OPENAI_MODEL;

		if (!githubToken) {
			console.error('Error: GITHUB_TOKEN is required');
			process.exit(1);
		}

		if (!openaiKey) {
			console.error('Error: OPENAI_API_KEY is required');
			process.exit(1);
		}

		try {
			const prId = parsePRUrl(prUrl);
			console.log(`\n🔍 Reviewing PR #${prId.prNumber} in ${prId.owner}/${prId.repo}...\n`);

			const github = new GitHubClient(githubToken);
			const pr = await github.getPullRequest(prId);
			const diffText = await github.getPullRequestDiff(prId);
			const chunks = parseDiff(diffText);

			console.log(`📄 Found ${chunks.length} changed files\n`);

			const logicAgent = new LogicReviewerAgent(openaiKey, openaiBaseUrl, openaiModel);
			const orchestrator = new ReviewOrchestrator([logicAgent]);

			const files = chunks.map((chunk) => ({ chunk }));
			const result = await orchestrator.reviewPR(pr.number, pr.title, pr.body, files);

			printReviewResult(result);

			if (options.postComment && result.totalComments > 0) {
				console.log('\n📝 Posting review to GitHub...');
				const commentBody = formatReviewAsMarkdown(result);
				await github.createIssueComment(prId, commentBody);
				console.log('✅ Review posted successfully!');
			}
		} catch (error) {
			console.error('Error:', error instanceof Error ? error.message : error);
			process.exit(1);
		}
	});

function printReviewResult(result: PRReviewResult): void {
	console.log('━'.repeat(60));
	console.log(`📊 Review Summary for PR #${result.prNumber}`);
	console.log('━'.repeat(60));
	console.log(`\nTotal issues found: ${result.totalComments}`);
	console.log(`  🔴 Errors: ${result.stats.errors}`);
	console.log(`  🟡 Warnings: ${result.stats.warnings}`);
	console.log(`  🔵 Suggestions: ${result.stats.suggestions}`);
	console.log(`  ⚪ Nitpicks: ${result.stats.nitpicks}`);

	if (result.totalComments > 0) {
		console.log('\n📝 Details:\n');

		for (const [filePath, comments] of result.commentsByFile) {
			console.log(`\n## ${filePath}`);
			for (const comment of comments) {
				const icon = {
					error: '🔴',
					warning: '🟡',
					suggestion: '🔵',
					nitpick: '⚪',
				}[comment.severity];

				console.log(`  ${icon} Line ${comment.lineNumber}: ${comment.message}`);
				if (comment.suggestion) {
					console.log(`     💡 Suggestion: ${comment.suggestion}`);
				}
			}
		}
	}

	console.log('\n' + '━'.repeat(60));
	console.log('Summary:');
	console.log(result.summary);
	console.log('━'.repeat(60));
}

function formatReviewAsMarkdown(result: PRReviewResult): string {
	const lines: string[] = [];

	lines.push('## 🤖 AI Code Review\n');
	lines.push(`**Total issues found:** ${result.totalComments}\n`);
	lines.push(`- 🔴 Errors: ${result.stats.errors}`);
	lines.push(`- 🟡 Warnings: ${result.stats.warnings}`);
	lines.push(`- 🔵 Suggestions: ${result.stats.suggestions}`);
	lines.push(`- ⚪ Nitpicks: ${result.stats.nitpicks}\n`);

	if (result.totalComments > 0) {
		lines.push('### Details\n');

		for (const [filePath, comments] of result.commentsByFile) {
			lines.push(`#### \`${filePath}\`\n`);
			for (const comment of comments) {
				const icon = {
					error: '🔴',
					warning: '🟡',
					suggestion: '🔵',
					nitpick: '⚪',
				}[comment.severity];

				lines.push(`${icon} **Line ${comment.lineNumber}:** ${comment.message}`);
				if (comment.suggestion) {
					lines.push(`> 💡 ${comment.suggestion}`);
				}
				lines.push('');
			}
		}
	}

	lines.push('---');
	lines.push('*Generated by PR Review Bot*');

	return lines.join('\n');
}

program.parse();
